### ISSUE TITLE
Not compatible with MagickWand 7.05?

### ISSUE THREAD

**Issue by zzhawk** [Opendigitalradio/ODR-PadEnc#3]
I make it compile by doing:

In sls.h :

include <wand/magick_wand.h>   =>    #  include <MagickWand/MagickWand.h>

In sls.cpp:

MagickResizeImage(m_wand, width, height, LanczosFilter,1) => MagickResizeImage(m_wand, width, height, LanczosFilter)

Otherwise, it will throw a fatal error...

Hopefully that's the fix, not sure... Please look into it if you get a chance, thank you!

**Comment by basicmaster** [comment]
ODR-PadEnc currently requires MagickWand in version 6. This is not mentioned in the README, but I will add a hint (thanks for pointing this out).

The problem with version 7 is that the MagickWand API is different. Hence ODR-PadEnc will not work out-of-the-box with v7 (as you noticed).

Debian and Ubuntu still package version 6 in all releases, as far as I can see. Furthermore the lib developers still maintain v6. So there seems currently no need to update to v7.

Do you have a specific reason to use v7? Would it be a problem for you to use v6 instead?

**Comment by zzhawk** [comment]
Thanks for the fast reply.

Nop, no special reason using v7. Just downloaded newest version this morning when dealing with a new PC. Not sure if the Ubuntu I am using include the v6, since the ODR-PadEnc can not detect it when  configure. I will consider using 6 instead, but it works fine now with the modification above. I have not tested the pictures yet (and does not need it at this point) but the pads are working great! I guess I just bypassed the problem but not actually fixed it.

Anyway, all good . Thanks again!

**Comment by basicmaster** [comment]
Which Ubuntu version do you use? And did you install the packet `libmagickwand-dev`?

Indeed, your solution is just a workaround - you will run into problems when the files that you modified will get updated in the repo sometime and you try to update your local repo copy. So I recommend to remove v7 and switch to v6 (if you have no other requirement to use v7).

**Comment by zzhawk** [comment]
Ubuntu 15.10

And I installed libmagickwand-dev.

Anyway, I uninstalled the v7 and installed v6, re-downloaded and re-installed the ODR-PadEnc. Now everything works well! Thanks for the support!

**Comment by basicmaster** [comment]
Great that it works for you; thanks for the feedback!

**Comment by basicmaster** [comment]
I just updated ODR-PadEnc to work with v6 as well as v7, as OpenSuse seems to start using v7.
