### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by zygmund2000** [Opendigitalradio/ODR-PadEnc#4]
I have compilation error without magickwand or I don't know how to do that.

**Comment by basicmaster** [comment]
This is quite general - more details are needed to be able to help you:
- what Linux distribution/version do you use?
- which commands did you use for compilation?
- what output did they return?

**Comment by zygmund2000** [comment]
Debian 64, summary info I see magickwand disabled, but during make stops with error 2.
./bootstrap
./configure
make - with libmagickwand-dev is ok, without error

**Comment by basicmaster** [comment]
OK, interesting. Could you please provide the complete output of the make command, when the error occurs?

**Comment by zygmund2000** [comment]
CXX      src/odr_padenc-odr-padenc.o
src/odr-padenc.cpp: In function ‘int main(int, char**)’:
src/odr-padenc.cpp:274:43: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘DABCharset’ [-Wformat=]
            user_charset, dl_params.charset);
                                           ^
  CXX      src/odr_padenc-common.o
  CXX      src/odr_padenc-pad_common.o
  CXX      src/odr_padenc-dls.o
  CXX      src/odr_padenc-sls.o
src/sls.cpp: In member function ‘bool SLSManager::encodeFile(const string&, int, bool)’:
src/sls.cpp:413:9: error: ‘ret’ was not declared in this scope
         ret = -1;
         ^~~


make[1]: *** [src/odr_padenc-sls.o] Error 1

I didn't paste all because it's not in english.

**Comment by basicmaster** [comment]
This is indeed a bug, thanks for reporting! I will fix it later today.

**Comment by basicmaster** [comment]
The bug is fixed now in the `next` branch. You can change to it with `git checkout next`.
