### ISSUE TITLE
PadEnc did not rotate through the images in the images directory.

### ISSUE THREAD

**Issue by Highspeedy** [Opendigitalradio/ODR-PadEnc#6]
System:

ARM 64
Linux-Kernel : 5.4.36-rockchip64
ODR-PadEnc: v2.3.0-17-g11767aa
ImageMagick: 6.9.10-23 Q16 aarch64 20190101

After starting the ODR-PadEnc in a shell the first image in the images directory , if it is one in it, will encoded. 

>odr-padenc -v -d ./Pic1 -t ./1_prog_dls_in.fifo -o ./1_prog_pad.fifo -e

But every new image in the folder not. Breaking ODR-PadEnc with [CTRL]-[C] is impossible too. Any idea, DLS seems to work. What's wrong ?

>ODR-PadEnc v2.3.0-17-g11767aa - DAB PAD encoder for MOT Slideshow and DLS
>
>By CSP Innovazione nelle ICT s.c.a r.l. (http://rd.csp.it/) and
>Opendigitalradio.org
>
>Reads image data from the specified directory, DLS text from a file,
>and outputs PAD data to the given FIFO.
>  https://opendigitalradio.org
>
>ODR-PadEnc encoding Slideshow from 'Pic1' and DLS from './1_prog_dls_in.fifo' to './1_prog_pad.fifo' (PAD length: 58)
>ODR-PadEnc using charset UTF-8 (15)
>ODR-PadEnc converting DLS texts to Complete EBU Latin
>ODR-PadEnc using burst PAD encoder
>ODR-PadEnc using ImageMagick version 'ImageMagick 6.9.10-23 Q16 aarch64 20190101 https://imagemagick.org'
>^C...ODR-PadEnc exits...

Thanks.

Martin

**Comment by Highspeedy** [comment]
Issue "solved". PadEnc works only properly if DLS text will continuesly  receive the FIFO file. If not, recoding and inserting pictures will not work.

**Comment by basicmaster** [comment]
(sorry for the late answer)

For the DLS input, it is indeed not possible to use a FIFO - here a FIFO can only (or rather must) be used for the PAD output.
