### ISSUE TITLE
odr-padenc hangs

### ISSUE THREAD

**Issue by vanhauser-thc** [Opendigitalradio/ODR-PadEnc#9]
freshly compiled from master:
```
ODR-PadEnc (master) # echo test > dls.txt
ODR-PadEnc (master) # ./odr-padenc -v -r -t ./dls.txt -o ./init.pad -s 1 -l 5
ODR-PadEnc v3.0.0 - DAB PAD encoder for MOT Slideshow and DLS

By CSP Innovazione nelle ICT s.c.a r.l. (http://rd.csp.it/) and
Opendigitalradio.org

Reads image data from the specified directory, DLS text from a file,
and outputs PAD data to the given FIFO.
  https://opendigitalradio.org

ODR-PadEnc encoding DLS from './dls.txt' to './init.pad'. No Slideshow.
ODR-PadEnc using charset UTF-8 (15)
ODR-PadEnc converting DLS texts to Complete EBU Latin
ODR-PadEnc using ImageMagick version 'ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org'
[... and then hangs here forever]
```
what could cause this hang?
With a (much) older version of odr-padenc (on a different system) this worked fine.

(and another issue I found - if I specify `-o /tmp/foo.pad` a socket is tried to be created with the name `/tmp/tmp/foo.pad` which of course fails)

**Comment by mpbraendli** [comment]
Hi,
Since you upgraded from v2 to v3, did you look into the incompatible changes? The output is not anymore a fifo.
mpb

**Comment by vanhauser-thc** [comment]
Why are you asking a question but closing the issue?
That the output is not a fifo is not my issue here. 
Isnt that command creating the output file /tmp/foo.pad in this example? It stays with 0 length for me and the command never completes.

**Comment by vanhauser-thc** [comment]
ah it seems the output is not a file, but a socket now ... damn...

**Comment by mpbraendli** [comment]
I try to follow semantic versioning for the tools, which means that you need to expect having to change something when the major version changes.

If you run into trouble again once you updated both odr-audioenc and odr-padenc, please don't hesitate to re-open the issue!
